### ISSUE TITLE
use a text file for storing and accessing api key

### ISSUE THREAD

**Issue by cherry-412** [RadinQue/immunity-bot#19]
when launching, the bot should check for **key.txt**.  this text file would contain the api key on the first line

if found:
- read first line, attempt login, see if validation worked
- if validated: log bot in, carry on  
- if validation failed: alert user, ask if they'd like to re-enter api key and then prompt for the api key. if no, exit

if not found:
- alert user, then prompt for the api key. perform validation as written above

no ecryption planned at this time, we'll have a separate issue for that if needed

**Comment by RadinQue** [comment]
Resolved in [01b68c9](https://github.com/RadinQue/immunity-bot/commit/01b68c9d6a1e747cec7c359a081ee929739dbdc2)
