### ISSUE TITLE
implement: prune

### ISSUE THREAD

**Issue by cherry-412** [RadinQue/immunity-bot#9]
- the command "prune" "[int amount]" would allow to delete previous messages up to a stated amount of messages
- "prune" as is without amount stated should alert the user that they require the amount and not perform any deletion of messages
- double check that the bot cannot run over the stated amount
- should probably have a hardcoded limit of perhaps 50 just in case.

**Comment by RadinQue** [comment]
Implemented in b27c3100892d8b61acd4e1d5c2cdb2731bf830dd, feel free to test and reopen if there're issues.
